export const dummyData = [
  {
    id: 1,
    nama: "Adi Ngareng",
    posisi: "Staff Manager",
    nilaiSkor: 0.907,
    peringkat: 1,
    avatar: "https://img.daisyui.com/images/profile/demo/2@94.webp",
    no_wa: "+6281234567890",
  },
  {
    id: 2,
    nama: "Budi Santoso",
    posisi: "Marketing Executive",
    nilaiSkor: 0.856,
    peringkat: 2,
    avatar: "https://img.daisyui.com/images/profile/demo/3@94.webp",
    no_wa: "+6282345678901",
  },
  {
    id: 3,
    nama: "Citra Lestari",
    posisi: "HR Specialist",
    nilaiSkor: 0.832,
    peringkat: 3,
    avatar: "https://img.daisyui.com/images/profile/demo/4@94.webp",
    no_wa: "+6283456789012",
  },
  {
    id: 4,
    nama: "Dewi Kusuma",
    posisi: "Finance Analyst",
    nilaiSkor: 0.821,
    peringkat: 4,
    avatar: "https://img.daisyui.com/images/profile/demo/5@94.webp",
    no_wa: "+6284567890123",
  },
  {
    id: 5,
    nama: "Eko Prasetyo",
    posisi: "IT Support",
    nilaiSkor: 0.815,
    peringkat: 5,
    avatar: "https://img.daisyui.com/images/profile/demo/6@94.webp",
    no_wa: "+6285678901234",
  },
  //  {
  //    id: 6,
  //    nama: "Fani Wijaya",
  //    posisi: "Sales Manager",
  //    nilaiSkor: 0.798,
  //    peringkat: 6,
  //    avatar: "https://img.daisyui.com/images/profile/demo/7@94.webp",
  //    no_wa: "+6286789012345",
  //  },
  //  {
  //    id: 7,
  //    nama: "Gita Ayu",
  //    posisi: "Product Manager",
  //    nilaiSkor: 0.789,
  //    peringkat: 7,
  //    avatar: "https://img.daisyui.com/images/profile/demo/8@94.webp",
  //    no_wa: "+6287890123456",
  //  },
  //  {
  //    id: 8,
  //    nama: "Hadi Nugroho",
  //    posisi: "Operations Manager",
  //    nilaiSkor: 0.776,
  //    peringkat: 8,
  //    avatar: "https://img.daisyui.com/images/profile/demo/9@94.webp",
  //    no_wa: "+6288901234567",
  //  },
  //  {
  //    id: 9,
  //    nama: "Indra Setiawan",
  //    posisi: "Quality Assurance",
  //    nilaiSkor: 0.765,
  //    peringkat: 9,
  //    avatar: "https://img.daisyui.com/images/profile/demo/10@94.webp",
  //    no_wa: "+6289012345678",
  //  },
  //  {
  //    id: 10,
  //    nama: "Joko Widodo",
  //    posisi: "Customer Service",
  //    nilaiSkor: 0.752,
  //    peringkat: 10,
  //    avatar: "https://img.daisyui.com/images/profile/demo/11@94.webp",
  //    no_wa: "+6280123456789",
  //  },
];
